### PR TITLE
Activate RANDOMDELAY in cron.d template

### PR DESCRIPTION
**Pull request by nkadel-skyhook**
Signed-off-by: Nico Kadel-Garcia <nkadel@skyhook.com>

### Description

Provides RANDOMDELAY option for /etc/cron.d tasks

### Issues Resolved

https://github.com/chef-cookbooks/cron/issues/85

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by nkadel-skyhook** [comment]
The original pull request languished so long, and needed rebasing after time, that the git history was getting pretty strange. Creating new pull request. It's really only a few lines of code to activate a long functional cron.d option.

**Comment by nkadel-skyhook** [comment]
The continuous integration failure looks like some kind of ubuntu apt-get failure. It has nothing to with tmy pull request itself, as near as I can tell.

**Comment by nkadel-skyhook** [comment]
The travis-ci failure looks like a failure of "apt-get update" in the testing environment. I can't fix that. Is there a graceful way to trigger a re-run of he travis-ci check?

**Comment by mark-from-usds** [comment]
Is this actually resolved? Doesn't random_delay also need to be added to https://github.com/chef-cookbooks/cron/blob/master/resources/d.rb ? Right now I get "undefined method" when I try to use it.

**Pull request merged**
