### PR TITLE
Make sure that internal resource run during delayed execution

### LINKED ISSUE #53: Provider does not create cron.d files when run from a ruby_block that it self was run as a :delayed notification
If the CronD resource is created and run from a *ruby_block* that was itself run as a *:delayed* notification from yet another resource, then the internal *template* and *file* providers (for *:create* and *:delete* actions, respectively) never trigger. 

Chef-client reports the cron_d resource as up to date, but there is no corresponding /etc/cron.d file. This is because the *update_by_last_action* is false as the internal *file* or *template* resource has not yet run.

Attaching a simple fix via pull request shortly.

### PR DESCRIPTION
**Pull request by alexderz**
Fixes #53

### CODE REVIEW

**Comment by scalp42** [comment]
LGTM

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @alexderz

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by tas50** [comment]
This shouldn't be necessary now that we use inline resources in Chef 11+.  If this is still an issue do let me know.

**Pull request closed without merging**
