### PR TITLE
Multiple commands

### PR DESCRIPTION
**Pull request by jmauro**
This is link to https://github.com/opscode-cookbooks/cron/issues/50

### CODE REVIEW

**Comment by pecigonzalo** [comment]
Any ideas to merge this? Sometimes different files do not cut it, and the cleanup on modifications is a PITA.

**Comment by chasebolt** [comment]
I think the best pattern is one file per resource. It makes for a cleaner coding pattern and keeps the library simple. My vote would be to close this PR with no merge.

**Comment by pecigonzalo** [comment]
I actually think thats an anti pattern for cron and as i said makes it actually dirtier unless you are running stateless infrastructure as there are constant leftovers on cron name modification etc.

**Comment by nkadel-skyhook** [comment]
> I actually think thats an anti pattern for cron

I agree with pecigonzalo. There are many classes of cron job with associated tasks, such as the publication, compression, and expiration of client deliverables, that would benefit from being in a single more easily managed /etc/cron.d/[task] filename.

**Comment by nkadel-skyhook** [comment]
On further thought, this sounds like an even better idea. When there a set of scheduled tasks and a single task is added or deleted to that list, maintaning them as distinct recipes can often demand *deleting* one of the tasks instead of doing them as a set. I'm particularly thinking backup tasks like "rsnapshot", where the extremely short rotation task for "monthly" snapshots needs to occur before the weekly or daily task, or a snapshot can be trimmed confusingly and unexpectedly.

**Comment by nkadel-skyhook** [comment]
This has been sitting idle for over 2 years, and now conflicts. I suggest rebasing it before trying to merge it.

**Comment by jmauro** [comment]
Hello,

Will try to do it asap.

**Comment by tas50** [comment]
Ping @jmauro on the rebase.

**Comment by tas50** [comment]
@jmauro I'm going to close this out at this point since we've merged all the resources in this cookbook into core Chef. If you still want to see this fix go in please make the change against the resource in the Chef repo itself and we'll get it reviewed / merged in promptly (promise).

**Comment by jmauro** [comment]
Fine by me.

**Pull request closed without merging**
