### PR TITLE
Convert cron_d LWRP to Chef 12.5 Custom Resource

### PR DESCRIPTION
**Pull request by veetow**
Chef Summit Hack Day!

### CODE REVIEW

**Comment by tas50** [comment]
I'm going to get final releases with Chef 11 support out the door and then I'd love to ship this.

**Comment by tas50** [comment]
@veetow Can you rebase this and add the now create_if_missing action that was added since this work was done.

**Comment by veetow** [comment]
@tas50 Sorry, somehow I missed your ask for a rebase.  I'll try to get to it ASAP.

**Comment by veetow** [comment]
Rebased (history rewrite). Tests pass on my end.

**Comment by tas50** [comment]
Thanks for this initial work. I picked up the torch and we converted the cookbook over to a custom resource in the last release

**Pull request closed without merging**
