### PR TITLE
adding action create_if_missing

### PR DESCRIPTION
**Pull request by chasebolt**
need the ability to create crons in dev, but not manage them afterwards so developers can make changes without fear or chef overwriting.

also updates spec to have full coverage along with testing  `action :delete`

### CODE REVIEW

**Comment by chasebolt** [comment]
paging @someara 

can you kindly pull this in for me? :grin:

**Comment by tas50** [comment]
It's probably time to remove the updated resource mess in the LWRP and just do use_inline_resources.  It would greatly simplify the code and it would just do the right thing for users.

**Comment by chasebolt** [comment]
agreed but right now this was a 15 min cleanup versus a rewrite.

i just noticed issue PR #64 has already converted it to the new resource style. I will rebase my changes off of that.

**Comment by tas50** [comment]
Looks like this broke deletion as well as the cron.d emulation.  I'm going to back out part of the template changes.

**Comment by chasebolt** [comment]
test-kitchen checks out fine and it has a spec for action :delete

do you have more details on this?

**Comment by tas50** [comment]
I've converted the LWRP to inline resources with a fix for the issue and expanded the test kitchen setup for the create_if_missing action https://github.com/chef-cookbooks/cron/pull/66

**Comment by tas50** [comment]
This was the reported issue btw: https://github.com/chef-cookbooks/chef-client/issues/352

**Comment by chasebolt** [comment]
thanks for fixing it up and leaving the action in. surprised that error cropped up and was valid previously.

**Pull request merged**
